vich_uploader:
    db_driver: orm 
    metadata:
        type: attribute

    mappings:
        peinture_images:
            uri_prefix: '%peinture_images%'
            upload_destination: '%kernel.project_dir%/public%peinture_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false # pour que vich ne supprime pas du serveur 
            delete_on_remove: false # pour que vich ne supprime pas du serveur
